import React from 'react';
import ReactDOM from 'react-dom/client';
import { I18nextProvider, useTranslation } from 'react-i18next';
import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import App from './App';
import { LockScreenSlave } from './components/LockScreenSlave';
import { FloatingPreview } from './components/FloatingPreview';
import { EntertainmentPreview } from './components/EntertainmentPreview';
import { ErrorBoundary } from './components/ErrorBoundary';
import './styles/global.css';

// 中文语言包
const zhCN = {
  app: {
    title: 'CareBuddy',
    subtitle: '关爱健康，从每一次提醒开始',
    mainTitle: '该动了',
    mainSubtitle: '久坐不是倔强，起身才是日常',
    exerciseTitle: '运动库',
    exerciseSubtitle: '把运动变成日常习惯，让健康成为生活常态',
    statsTitle: '数据统计',
    statsSubtitle: '每一次小行动，都在悄悄保护你的身体',
  },
  nav: {
    main: '主界面',
    exercise: '运动库',
    stats: '统计',
  },
  tabs: {
    dashboard: '看板',
    exercise: '活动',
    stats: '统计',
  },
  dashboard: {
    countdown: '倒计时',
    upcoming: '当前:',
    runningReminders: '{{count}}个',
    pausedReminders: '{{count}}个暂停',
    remainingPercent: '剩余{{percent}}%',
    normal: '正常',
    paused: '已暂停',
    idle: '空闲中',
    idleHint: '检测到你已离开，提醒已暂停',
    pauseAll: '暂停所有提醒',
    resumeAll: '继续所有提醒',
    resetAll: '重置所有提醒',
    noActiveReminders: '暂无进行中的提醒',
    enableRemindersHint: '请在设置中开启提醒',
    todayStats: '今日统计',
    workMinutes: '运行时长',
    streakDays: '连续天数',
    minutes: '分钟',
    durationMinutes: 'min',
    durationHoursMinutes: 'h',
    days: '天',
    times: '次',
    entertainmentMode: '娱乐模式',
    entertainmentActive: '娱乐中',
    nextReminder: '下次提醒',
    showAll: '查看全部',
    showLess: '查看更少',
    entertainmentHint: '到点提醒一次休息',
  },
  stats: {
    sitBreaks: '休息次数',
    waterCups: '喝水次数',
    workMinutes: '工作分钟',
    exercisesCompleted: '运动次数',
    packagesCompleted: '套餐完成',
    totalExerciseMinutes: '运动时长',
    title: '健康统计',
    weeklyData: '本周数据',
    weeklyTrend: '本周运动趋势',
    monthlyMinutes: '本月运动时长',
    totalSummary: '总计',
    weeklyHabits: '本周习惯',
    monthlyHabits: '本月习惯',
    recordDays: '记录天数',
    day: '日',
    week: '周',
    month: '月',
    trackingTrend: '追踪 · 趋势',
    goalFeedback: '目标 · 反馈',
    streakDays: '连续达标',
    compositeScore: '综合达标',
    compositeLabel: '综合达标',
    vsLastWeek: '环比',
    goalEdit: '目标设定',
    editWeeklyGoal: '编辑周目标',
    reset: '重置默认',
    save: '保存',
    dayDetail: '当天明细',
    noData: '该天无数据',
    goalMet: '达标',
    goalNotMet: '未达标',
    goalsMet: '项达标',
    exerciseTrend: '运动时长',
    avgMinutes: '日均',
    exerciseMinutes: '运动时长(分钟)',
    thisWeekExercises: '运动',
    noWeeklyData: '暂无本周数据',
    noExerciseData: '暂无运动数据',
    target: '目标',
  },
  tasks: {
    sit: { title: '久坐提醒', desc: '该起来活动了' },
    water: { title: '喝水提醒', desc: '该喝口水了' },
    eye: { title: '护眼提醒', desc: '让眼睛休息一下' },
  },
  taskNames: {
    sit: '久坐提醒',
    water: '喝水提醒',
    eye: '护眼提醒',
  },
  taskDesc: {
    sit: '坐姿超过45分钟，起身活动1-2分钟',
    water: '每小时提醒喝一杯水，保持身体水分',
    eye: '每工作45分钟，远眺6米外放松眼睛20秒',
    default: '每{{interval}}分钟提醒一次',
  },
  time: {
    minutes: '分',
    seconds: '秒',
    count: '次',
    sec: '秒',
    group: '组',
  },
  buttons: {
    pause: '暂停',
    resume: '继续',
    resetAll: '全部重置',
    addTask: '添加提醒',
    gotIt: '我知道了',
  },
  settings: {
    title: '系统设置',
    language: '语言',
    languageDesc: '切换界面显示语言',
    lockScreenExercise: '锁屏运动',
    lockScreenExerciseDesc: '开启后，配有运动的提醒会在锁屏时带你做',
    noExerciseConfiguredHint: '总开关已开启，但还没有提醒配置锁屏运动，去各提醒的锁屏运动里配置吧',
    strictMode: '严格模式',
    strictModeDesc: '开启后锁屏无法中途退出，需完成设定的动作或者等待倒计时结束',
    strictModeWarningTitle: '警告',
    strictModeWarningDesc: '锁屏期间无法中途退出，需完成运动或等倒计时结束',
    strictModeWarningCancel: '取消',
    strictModeWarningConfirm: '我已了解，确认',
    theme: '主题',
    themeDesc: '选择浅色、深色或跟随系统',
    system: '跟随系统',
    light: '浅色',
    dark: '深色',
    autoUnlock: '自动解锁',
    autoUnlockDesc: '倒计时结束后自动解除锁屏',
    resetOnIdle: '空闲时重置',
    resetOnIdleDesc: '离开电脑后，提醒自动重新计时',
    autoStart: '开机自启',
    autoStartDesc: '系统启动时自动运行',
    idleThreshold: '多久算空闲',
    idleThresholdDesc: '超过这个时间没碰电脑，就先暂停提醒（分钟）',
    mergeReminders: '合并临近提醒',
    mergeRemindersDesc: '临近的提醒合并到一次锁屏，少打断你（分钟）',
    alertStyle: '提醒方式',
    modeNotifNoSettings: '当前模式无需额外配置',
    modeNotifNoSettingsDesc: '到点后通过系统通知弹窗提醒，几秒后自动消失，不打断工作',
    taskManagement: '提醒管理',
    taskLimitReached: '最多支持 12 个提醒，已达上限',
    editReminder: '编辑提醒',
    save: '保存',
    general: '通用设置',
    defaultReminder: '默认',
    reminderSubtitleInterval: '每 {{interval}} 分',
    reminderSubtitleDaily: '每天 {{time}}',
    scheduleType: '提醒节奏',
    interval: '时间间隔',
    fixedTime: '固定时间',
    time: '提醒时间',
    preNotify: '提前提醒（秒）',
    lockDuration: '锁屏时长',
    lockScreenExerciseEditor: '锁屏运动',
    lockScreenExerciseEditorDesc: '开启后，锁屏时带你做设定的运动',
    customizeExercise: '自定义',
    back: '返回',
    selectExerciseTitle: '选择锁屏运动',
    selectExerciseTitleFor: '为「{{title}}」选择锁屏运动',
    lockScreenExerciseModeHint: '锁屏运动仅在锁屏模式（且总开关开启）时生效，这里仍可提前配置',
    exerciseSelectedCount: '已选 {{count}} 个',
    exerciseAddButton: '添加运动',
    exerciseTooManyWarn: '已选 {{count}} 个，约 {{minutes}} 分钟，有点长了',
    exerciseEmptyWarn: '先选一个运动吧',
    deleteReminder: '删除提醒',
    addCustomReminder: '添加自定义提醒',
    newReminder: '新建提醒',
    reminderNamePlaceholder: '提醒名称',
    cancel: '取消',
    confirmAdd: '添加',
    done: '完成',
    seconds: '秒',
    modeNotification: '系统通知',
    modeNotificationDesc: '系统弹窗提醒，几秒后自动消失，不打断',
    modeLock: '锁屏提醒',
    modeLockDesc: '全屏锁屏，搭配活动，强制休息',
    modeFloating: '浮窗提醒',
    modeFloatingDesc: '浮窗胶囊，轻量交互不打扰',
    entertainmentMode: '娱乐模式',
    entertainmentModeEnabled: '启用娱乐模式',
    entertainmentModeEnabledDesc: '看视频、玩游戏时自动切换到轻松提醒，其它提醒暂时停下',
    entertainmentDisabledHint: '娱乐模式已关闭',
    entertainmentDisabledHintDesc: '开启后，可添加触发应用并设置休息提醒节奏',
    floatingOpacity: '浮窗透明度',
    floatingOpacityDesc: '浮窗胶囊的可见度，调低更不显眼',
    floatingSnoozeMinutes: '延后时长',
    floatingSnoozeMinutesDesc: '提醒弹出后，多久不操作就自动延后',
    entertainmentIdleThreshold: '无操作多久算离开',
    entertainmentIdleThresholdDesc: '看剧、玩游戏时你可能很久不碰鼠标。设长一点，可避免被误判离开而打断娱乐',
    entertainmentExitThreshold: '离开应用多久算退出',
    entertainmentExitThresholdDesc: '切出娱乐应用后，缓冲多久才真正退出娱乐模式（覆盖临时切窗口看一眼消息的场景）',
    entertainmentReminderMinutes: '休息提醒间隔',
    entertainmentReminderMinutesDesc: '娱乐模式中每隔多久提醒一次休息',
    entertainmentOpacity: '提醒胶囊透明度',
    entertainmentOpacityDesc: '娱乐提醒弹出时的胶囊透明度',
    entertainmentSnoozeMinutes: '自动延后时长',
    entertainmentSnoozeMinutesDesc: '提醒弹出后，多久不操作就自动延后',
    entertainmentApps: '娱乐应用',
    entertainmentAppsDesc: '这些应用在前台时，自动进入娱乐模式',
    addEntertainmentApp: '添加应用',
    selectRunningWindow: '选择当前运行窗口',
    selectWindowPlaceholder: '选择窗口（按进程名匹配）',
    noEntertainmentApps: '还没有添加娱乐应用',
    entertainmentCapsulePrefix: '娱乐 · ',
    entertainmentCapsuleIdle: '娱乐中',
    entertainmentDone: '完成',
  },
  exercise: {
    library: '医学级运动库',
    packages: '运动套餐',
    all: '全部',
    encourageIdle: '今天还没活动过，先舒展舒展吧',
    encourageStart: '动起来啦，保持这个节奏',
    encourageGood: '继续保持，身体会越来越舒服',
    characterMenu: '切换形象展示',
    characterSwitch: '切换形象（男/女）',
    characterMale: '形象展示男',
    characterFemale: '形象展示女',
    showRecommendation: '显示当前推荐',
    sectionTitle: '今日推荐',
    instructions: '执行说明',
    whyImportant: '为何重要',
    repetitions: '次数',
    items: '项',
    activities: '项运动',
    holdTime: '保持时间',
    sets: '组数',
    evidenceSource: '医学依据',
    complete: '完成',
    completed: '已完成',
    markComplete: '标记完成',
    guidedMode: '引导模式',
    quickStart: '快速开始',
    startPackage: '开始活动',
    finishPackage: '完成套餐',
    skip: '跳过',
    next: '下一个',
    exit: '退出',
    title: '运动提醒',
    packageComplete: '套餐完成！',
    priorityCore: '必做',
    priorityStrong: '推荐',
    priorityRecommend: '可选',
    prioritySupplement: '补充',
  },
  guided: {
    getReady: '准备开始',
    preparing: '准备开始…',
    prep: '预备',
    secondsRemaining: '剩余秒数',
    remainingCycles: '剩余 {{count}} 次',
    continuousHint: '保持节奏，连续完成',
    speaking: '语音播报中',
    completed: '完成！',
    returning: '即将返回',
    exit: '退出',
    slaveHint: '请在主屏完成引导活动',
  },
  lock: {
    title: '休息一下',
    done: '完成了',
    completed: '已完成',
    strictModeLabel: '严格模式',
    emergencyUnlock: '紧急解锁',
    emergencyUnlockTooltip: 'Windows: Alt+F4\nmacOS: Cmd+Q\n强退将不记录任何完成',
    lookAtMainDisplay: '请在主显示器完成操作',
    startExercise: '开始活动',
    nextExercise: '下一个',
    noExercises: '当前提醒未配置运动',
    finished: '运动完成',
  },
  window: {
    menu: '菜单',
    about: '关于',
    minimize: '最小化',
    closeToTray: '关闭到托盘',
  },
  timerCarousel: {
    title: '我的提醒',
    paused: '已暂停',
    empty: '暂无启用的提醒',
    pauseAll: '暂停全部',
    resumeAll: '继续全部',
    resetAll: '重置全部',
    taskPaused: '{{taskName}}已暂停',
    preNotificationBody: '即将提醒，请准备',
    allPaused: '全部提醒已暂停',
    autoResume: '后自动切换',
    remainingPercent: '剩余 {{percent}}%',
    statusNormal: '所有提醒正常运行',
    somePaused: '有提醒已暂停',
  },
  categories: {
    spine: '脊柱与骨骼',
    circulation: '血液循环',
    metabolism: '代谢激活',
    vision: '视力保护',
    wrist: '神经/腕部',
    'package-quick': '快速套餐',
    'package-standard': '标准套餐',
    'package-deep': '深度套餐',
  },
  statCards: {
    workMinutes: '运行时长',
    eyeCare: '护眼提醒',
    sitReminder: '久坐提醒',
    waterReminder: '喝水提醒',
    todayStats: '今日统计',
    todaySubtitle: '不是记流水账，是完成的动力感',
    todayExercise: '运动次数',
    exercise: '动作',
    package: '套餐',
    streakTooltip: '已连续达标 {{days}} 天',
    customReminders: '自定义提醒',
    healthMetrics: '健康指标',
    goalSettings: '指标设定',
    weeklyReport: '周报',
    noGoal: '未设目标',
    yesterday: '比昨天',
    exercise2: '运动',
    streakDays2: '连续天数',
  },
  floating: {
    triggered: '该休息了',
    done: '完成',
    snooze: '延后',
    currentReminder: '当前提醒',
    timeUp: '到时间了',
    snoozeFailed: '推迟失败，请重试',
    noReminder: '暂无提醒',
  },
  error: {
    title: '应用出现异常',
    reload: '重新加载',
  },
  common: {
    or: '或',
  },
};

// 英文语言包
const enUS = {
  app: {
    title: 'CareBuddy',
    subtitle: 'Build healthy habits, one reminder at a time',
    mainTitle: 'Time to Move',
    mainSubtitle: "Sitting isn't a lifestyle—standing up should be.",
    exerciseTitle: 'Exercise Library',
    exerciseSubtitle: 'Make movement a habit, and health a lifestyle',
    statsTitle: 'Statistics',
    statsSubtitle: 'Every small action is quietly protecting your body',
  },
  nav: {
    main: 'Main',
    exercise: 'Exercise',
    stats: 'Stats',
  },
  tabs: {
    dashboard: 'Dashboard',
    exercise: 'Move',
    stats: 'Stats',
  },
  dashboard: {
    countdown: 'Countdown',
    upcoming: 'Current:',
    runningReminders: '{{count}} running',
    pausedReminders: '{{count}} paused',
    remainingPercent: '{{percent}}% remaining',
    normal: 'Normal',
    paused: 'Paused',
    idle: 'Idle',
    idleHint: "You've been away, reminders paused",
    pauseAll: 'Pause All',
    resumeAll: 'Resume All',
    resetAll: 'Reset All',
    noActiveReminders: 'No active reminders',
    enableRemindersHint: 'Enable reminders in settings',
    todayStats: "Today's Stats",
    workMinutes: 'Work Time',
    streakDays: 'Streak Days',
    minutes: 'min',
    durationMinutes: 'min',
    durationHoursMinutes: 'h',
    days: 'd',
    times: 'times',
    entertainmentMode: 'Entertainment Mode',
    entertainmentActive: 'In Entertainment',
    nextReminder: 'Next reminder',
    showAll: 'Show all',
    showLess: 'Show less',
    entertainmentHint: 'Reminds you to take a break when due',
  },
  stats: {
    sitBreaks: 'Sit Breaks',
    waterCups: 'Water Cups',
    workMinutes: 'Work Minutes',
    exercisesCompleted: 'Exercises',
    packagesCompleted: 'Packages',
    totalExerciseMinutes: 'Exercise Minutes',
    title: 'Statistics',
    weeklyData: 'Weekly Data',
    weeklyTrend: 'Weekly Trend',
    monthlyMinutes: 'Monthly Minutes',
    totalSummary: 'Total Summary',
    weeklyHabits: 'Weekly Habits',
    monthlyHabits: 'Monthly Habits',
    recordDays: 'Record Days',
    day: 'd',
    week: 'Week',
    month: 'Month',
    trackingTrend: 'Tracking · Trend',
    goalFeedback: 'Goal · Feedback',
    streakDays: 'Streak',
    compositeScore: 'Composite',
    compositeLabel: 'Composite',
    vsLastWeek: 'vs Last',
    goalEdit: 'Goal Setting',
    editWeeklyGoal: 'Edit Weekly Goals',
    reset: 'Reset',
    save: 'Save',
    dayDetail: 'Day Detail',
    noData: 'No data for this day',
    goalMet: 'Met',
    goalNotMet: 'Not met',
    goalsMet: 'goals met',
    exerciseTrend: 'Exercise Time',
    avgMinutes: 'Avg',
    exerciseMinutes: 'Exercise Minutes',
    thisWeekExercises: 'Exercise',
    noWeeklyData: 'No weekly data',
    noExerciseData: 'No exercise data',
    target: 'Target',
  },
  exercise: {
    library: 'Exercise Library',
    packages: 'Exercise Packages',
    all: 'All',
    encourageIdle: "Haven't moved yet today — stretch a bit?",
    encourageStart: "You're moving — keep it up",
    encourageGood: 'Keep moving — your body will feel better and better',
    characterMenu: 'Switch character',
    characterSwitch: 'Switch character (male/female)',
    characterMale: 'Character · Male',
    characterFemale: 'Character · Female',
    showRecommendation: 'Show recommendation',
    sectionTitle: "Today's Picks",
    instructions: 'Instructions',
    whyImportant: 'Why It Matters',
    repetitions: 'Repetitions',
    items: 'activities',
    activities: 'exercises',
    holdTime: 'Hold Time',
    sets: 'Sets',
    evidenceSource: 'Medical Evidence',
    complete: 'Complete',
    completed: 'Completed',
    markComplete: 'Mark Complete',
    guidedMode: 'Guided Mode',
    quickStart: 'Quick Start',
    startPackage: 'Start Moving',
    finishPackage: 'Finish Package',
    skip: 'Skip',
    next: 'Next',
    exit: 'Exit',
    title: 'Exercise Reminder',
    packageComplete: 'Package Complete!',
    priorityCore: 'Core',
    priorityStrong: 'Recommended',
    priorityRecommend: 'Optional',
    prioritySupplement: 'Supplement',
  },
  guided: {
    getReady: 'Get Ready',
    preparing: 'Preparing…',
    prep: 'Prepare',
    secondsRemaining: 'seconds remaining',
    remainingCycles: '{{count}} reps remaining',
    continuousHint: 'Keep pace, complete continuously',
    speaking: 'Voice Guide Active',
    completed: 'Complete!',
    returning: 'Returning',
    exit: 'Exit',
    slaveHint: 'Complete guided move on main screen',
  },
  lock: {
    title: 'Break Time',
    done: 'Done',
    completed: 'Completed',
    strictModeLabel: 'Strict mode',
    emergencyUnlock: 'Emergency unlock',
    emergencyUnlockTooltip: 'Windows: Alt+F4\nmacOS: Cmd+Q\nForce quit won\'t record any completion',
    lookAtMainDisplay: 'Please complete the action on the main display',
    startExercise: 'Start Moving',
    nextExercise: 'Next',
    noExercises: 'No exercises configured for this reminder',
    finished: 'Exercise complete',
  },
  tasks: {
    sit: { title: 'Sit Reminder', desc: 'Time to stand up' },
    water: { title: 'Water Reminder', desc: 'Time to drink water' },
    eye: { title: 'Eye Reminder', desc: 'Rest your eyes' },
  },
  taskNames: {
    sit: 'Stand Up',
    water: 'Drink Water',
    eye: 'Rest Eyes',
  },
  taskDesc: {
    sit: 'Sit for 45+ min, stand and move for 1-2 min',
    water: 'Drink a glass of water every hour',
    eye: 'Rest your eyes, look 20ft away for 20s',
    default: 'Remind every {{interval}} minutes',
  },
  settings: {
    title: 'Settings',
    language: 'Language',
    languageDesc: 'Switch interface language',
    lockScreenExercise: 'Lock-screen Exercise',
    lockScreenExerciseDesc: 'Reminders with exercises will guide you through them on the lock screen',
    noExerciseConfiguredHint: 'Master switch is on, but no reminder has exercises yet — set them up in each reminder',
    strictMode: 'Strict Mode',
    strictModeDesc: 'After enabling, you cannot exit mid-lock. You must complete configured actions or wait for the countdown to end.',
    strictModeWarningTitle: 'Warning',
    strictModeWarningDesc: "You can't exit mid-lock — finish the exercise or wait for the countdown",
    strictModeWarningCancel: 'Cancel',
    strictModeWarningConfirm: 'I understand, confirm',
    theme: 'Theme',
    themeDesc: 'Choose light, dark, or system theme',
    system: 'System',
    light: 'Light',
    dark: 'Dark',
    autoUnlock: 'Auto Unlock',
    autoUnlockDesc: 'Auto dismiss lock screen when countdown ends',
    resetOnIdle: 'Reset on Idle',
    resetOnIdleDesc: 'Reminders restart their countdown after you step away',
    autoStart: 'Auto Start',
    autoStartDesc: 'Launch app on system startup',
    idleThreshold: 'Idle after',
    idleThresholdDesc: 'Minutes of no activity before reminders pause',
    mergeReminders: 'Merge nearby reminders',
    mergeRemindersDesc: 'Merge nearby reminders into one lock screen to avoid repeated interruptions (minutes)',
    alertStyle: 'Alert Style',
    modeNotifNoSettings: 'No additional settings needed',
    modeNotifNoSettingsDesc: 'When a reminder fires, a system notification appears and auto-dismisses',
    taskManagement: 'My Reminders',
    taskLimitReached: 'Up to 12 reminders supported, limit reached',
    editReminder: 'Edit Reminder',
    save: 'Save',
    general: 'Settings',
    defaultReminder: 'Default',
    reminderSubtitleInterval: 'Every {{interval}} min',
    reminderSubtitleDaily: 'Daily at {{time}}',
    scheduleType: 'Trigger rhythm',
    interval: 'Interval',
    fixedTime: 'Fixed Time',
    time: 'Daily Time',
    preNotify: 'Pre-notify (sec)',
    lockDuration: 'Lock Duration',
    lockScreenExerciseEditor: 'Lock-screen Exercise',
    lockScreenExerciseEditorDesc: 'Guided exercise plays on the lock screen',
    customizeExercise: 'Customize',
    back: 'Back',
    selectExerciseTitle: 'Choose Lock-screen Exercises',
    selectExerciseTitleFor: 'Choose exercises for "{{title}}"',
    lockScreenExerciseModeHint: 'Lock-screen exercises only take effect in Lock mode (with the master switch on). You can configure them here in advance.',
    exerciseSelectedCount: '{{count}} selected',
    exerciseAddButton: 'Add Exercise',
    exerciseTooManyWarn: "{{count}} selected, ~{{minutes}} min — that's a lot",
    exerciseEmptyWarn: 'Pick at least one exercise',
    deleteReminder: 'Delete Reminder',
    addCustomReminder: 'Add Custom Reminder',
    newReminder: 'New Reminder',
    reminderNamePlaceholder: 'Reminder name',
    cancel: 'Cancel',
    confirmAdd: 'Add',
    done: 'Done',
    seconds: 'sec',
    modeNotification: 'System Notification',
    modeNotificationDesc: 'A popup appears and auto-dismisses in a few seconds',
    modeLock: 'Lock Screen',
    modeLockDesc: 'Full-screen lock, guided move, enforced break',
    modeFloating: 'Floating Capsule',
    modeFloatingDesc: 'Floating capsule, lightweight, stays out of your way',
    entertainmentMode: 'Entertainment',
    entertainmentModeEnabled: 'Enable Entertainment Mode',
    entertainmentModeEnabledDesc: 'While you watch videos or play games, switch to gentle rest reminders and pause other alerts',
    entertainmentDisabledHint: 'Entertainment mode is off',
    entertainmentDisabledHintDesc: 'Turn on to add apps and set your rest reminder cadence',
    floatingOpacity: 'Floating Opacity',
    floatingOpacityDesc: 'How visible the capsule is — lower is subtler',
    floatingSnoozeMinutes: 'Snooze Duration',
    floatingSnoozeMinutesDesc: 'Auto-snooze after this many idle minutes',
    entertainmentIdleThreshold: 'Idle before marked away',
    entertainmentIdleThresholdDesc: 'While watching or gaming you may not touch the mouse. Raise this so you aren\'t wrongly marked away and interrupted',
    entertainmentExitThreshold: 'Exit delay after leaving app',
    entertainmentExitThresholdDesc: 'Keep the mode active this long after switching away, before truly exiting (covers briefly alt-tabbing to check a message)',
    entertainmentReminderMinutes: 'Rest reminder interval',
    entertainmentReminderMinutesDesc: 'How often to remind a rest while in entertainment mode',
    entertainmentOpacity: 'Capsule opacity',
    entertainmentOpacityDesc: 'Capsule opacity when a rest reminder appears',
    entertainmentSnoozeMinutes: 'Auto-snooze delay',
    entertainmentSnoozeMinutesDesc: 'Minutes of no action before a reminder auto-snoozes',
    entertainmentApps: 'Entertainment Apps',
    entertainmentAppsDesc: 'Automatically enter entertainment mode when any of these apps is in the foreground',
    addEntertainmentApp: 'Add App',
    selectRunningWindow: 'Select Running Window',
    selectWindowPlaceholder: 'Select a window (matched by process name)',
    noEntertainmentApps: 'No entertainment apps added yet',
    entertainmentCapsulePrefix: 'Entertainment · ',
    entertainmentCapsuleIdle: 'Watching',
    entertainmentDone: 'Done',
  },
  buttons: {
    pause: 'Pause',
    resume: 'Resume',
    resetAll: 'Reset All',
    addTask: 'Add Task',
    gotIt: 'Got It',
  },
  time: {
    minutes: 'min',
    seconds: 's',
    count: ' reps',
    sec: 's',
    group: ' sets',
  },
  window: {
    menu: 'Menu',
    about: 'About',
    minimize: 'Minimize',
    closeToTray: 'Close to Tray',
  },
  timerCarousel: {
    title: 'My Reminders',
    paused: 'Paused',
    empty: 'No active reminders',
    pauseAll: 'Pause All',
    resumeAll: 'Resume All',
    resetAll: 'Reset All',
    taskPaused: '{{taskName}} paused',
    preNotificationBody: 'Coming up soon, get ready',
    allPaused: 'All reminders paused',
    autoResume: 's auto resume',
    remainingPercent: '{{percent}}% remaining',
    statusNormal: 'All reminders active',
    somePaused: 'Some reminders paused',
  },
  categories: {
    spine: 'Spine & Bones',
    circulation: 'Blood Circulation',
    metabolism: 'Metabolism',
    vision: 'Eye Protection',
    wrist: 'Nerve & Wrist',
    'package-quick': 'Quick Pack',
    'package-standard': 'Standard Pack',
    'package-deep': 'Deep Pack',
  },
  statCards: {
    workMinutes: 'Work Time',
    eyeCare: 'Eye Care',
    sitReminder: 'Sit Reminder',
    waterReminder: 'Water Reminder',
    todayStats: "Today's Stats",
    todaySubtitle: 'Every small action is quietly protecting your body',
    todayExercise: "Exercise Count",
    exercise: 'Exercises',
    package: 'Packages',
    streakTooltip: '{{days}} day streak',
    customReminders: 'Custom Reminders',
    healthMetrics: 'Health Metrics',
    goalSettings: 'Goal Settings',
    weeklyReport: 'Report',
    noGoal: 'No Goal',
    yesterday: 'vs yesterday',
    exercise2: 'Exercise',
    streakDays2: 'Streak Days',
  },
  floating: {
    triggered: 'Time to Rest',
    done: 'Done',
    snooze: 'Snooze',
    currentReminder: 'Current reminder',
    timeUp: "Time's up",
    snoozeFailed: 'Snooze failed, try again',
    noReminder: 'No reminder',
  },
  error: {
    title: 'Something went wrong',
    reload: 'Reload',
  },
  common: {
    or: 'or',
  },
};

// 同步初始化 i18n
i18n.use(initReactI18next).init({
  resources: {
    'zh-CN': { translation: zhCN },
    'en-US': { translation: enUS },
  },
  lng: 'zh-CN',
  fallbackLng: 'zh-CN',
  interpolation: {
    escapeValue: false,
  },
  react: {
    useSuspense: false,
  },
});

const params = new URLSearchParams(window.location.search);
const mode = params.get('mode');

let RootComponent: React.ReactNode;
if (mode === 'lock_slave') {
  RootComponent = <LockScreenSlave />;
} else if (mode === 'floating') {
  RootComponent = <FloatingPreview />;
} else if (mode === 'entertainment') {
  RootComponent = <EntertainmentPreview />;
} else {
  RootComponent = <App />;
}

ReactDOM.createRoot(document.getElementById('app') as HTMLElement).render(
  <ErrorBoundary>
    <I18nextProvider i18n={i18n}>
      {RootComponent}
    </I18nextProvider>
  </ErrorBoundary>
);
